"""added monitor table

Revision ID: 1e05f2ed45b4
Revises: aa458dcf92c5
Create Date: 2025-04-10 21:30:52.536106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e05f2ed45b4'
down_revision = 'aa458dcf92c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('time_next_ping', sa.DateTime(), nullable=False),
    sa.Column('seconds_to_next_ping', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitor_time_next_ping'), ['time_next_ping'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitor_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitor_user_id'))
        batch_op.drop_index(batch_op.f('ix_monitor_time_next_ping'))

    op.drop_table('monitor')
    # ### end Alembic commands ###
